name: slider_button
description: Customizable slider button widget for activating/deactivating some event.
version: 2.1.1
homepage: https://github.com/anirudhsharma392/Slider-Button

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

